steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f', 'navbar-app/Dockerfile.callback',
        '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO/callback-server:$SHORT_SHA',
        'navbar-app'
      ]
images:
  - '$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO/callback-server:$SHORT_SHA'
