name: Deploy Backend to Cloud Run

on:
  push:
    branches: [ main ]
    paths:
      - 'navbar-app/backend/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Auth to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 470.0.0'

      - name: Configure Docker auth
        run: gcloud auth configure-docker --quiet

      - name: Build & Push Image
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          IMAGE=gcr.io/${PROJECT_ID}/navbar-backend:${GITHUB_SHA}
          docker build -t $IMAGE navbar-app/backend
          docker push $IMAGE
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: navbar-backend
          image: ${{ env.IMAGE }}
          region: us-central1
          allow-unauthenticated: true
          env_vars: |
            PORT=3002
          secrets: |
            MONGO_URI=MONGO_URI:latest

      - name: Output Service URL
        run: echo "Service URL -> ${{ steps.deploy.outputs.url }}"
